# Generated by Django 5.1.2 on 2024-10-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('location_name', models.CharField(max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportOrderWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('transport_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='app.transportorder')),
                ('waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.waypoint')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('transport_order', 'waypoint')},
            },
        ),
    ]
