# name: Deploy

# on:
#     pull_request:
#         branches:
#             - staging

# jobs:
#     build:
#         runs-on: ubuntu-latest
#         env:
#             ENVIRONMENT: production

#         steps:
#             - uses: actions/checkout@v4
#             - name: Set up Python
#               uses: actions/setup-python@v5
#               with:
#                   python-version: 3.10.11
#             - name: Install dependencies
#               run: |
#                   python -m pip install --upgrade pip
#                   pip install -r requirements.txt
#                   python ./tms/manage.py seed
#                   python ./tms/manage.py collectstatic --noinput
#                 #   python ./tms/manage.py migrate
#                 #   python ./tms/manage.py test

# python ./tms/manage.py migrate && python ./tms/manage.py collectstatic --noinput && python ./tms/manage.py seed
# export PATH=$PATH:/usr/local/python3/bin && pip install gunicorn && pip install -r requirements.txt && python ./tms/manage.py migrate && python ./tms/manage.py collectstatic --noinput && python ./tms/manage.py seed